package oodj.assignment.v1;

import Class.User;
import java.io.*;
import java.io.File;
import java.io.IOException;
import java.io.FileWriter;  
import javax.swing.JOptionPane;
import java.util.Arrays; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author New
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Reg_GUI
     */
    
    //restrict access externally of attributes
    
    
    
    public Register() {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        reg_label = new javax.swing.JLabel();
        reg_panel = new javax.swing.JPanel();
        firstname_lab = new javax.swing.JLabel();
        firstname_txt = new javax.swing.JTextField();
        lastname_lab = new javax.swing.JLabel();
        lastname_txt = new javax.swing.JTextField();
        addr_lab = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addr_txt = new javax.swing.JTextArea();
        pos_lab = new javax.swing.JLabel();
        pos_combox = new javax.swing.JComboBox<>();
        email_lab = new javax.swing.JLabel();
        email_txt = new javax.swing.JTextField();
        pwd_lab = new javax.swing.JLabel();
        pwd_txt = new javax.swing.JPasswordField();
        crm_pwd_lab = new javax.swing.JLabel();
        crm_pwd_txt = new javax.swing.JPasswordField();
        contact_no = new javax.swing.JLabel();
        contact_no_txt = new javax.swing.JTextField();
        crm_reg_but = new javax.swing.JButton();
        bac_but = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Register"); // NOI18N

        reg_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        reg_label.setText("Register");

        firstname_lab.setText("First Name:");

        firstname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_txtActionPerformed(evt);
            }
        });

        lastname_lab.setText("Last Name:");

        lastname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastname_txtActionPerformed(evt);
            }
        });

        addr_lab.setText("Address:");

        addr_txt.setColumns(20);
        addr_txt.setRows(5);
        jScrollPane2.setViewportView(addr_txt);

        pos_lab.setText("Register as:");

        pos_combox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Customer" }));
        pos_combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pos_comboxActionPerformed(evt);
            }
        });

        email_lab.setText("Email:");

        pwd_lab.setText("Password:");

        crm_pwd_lab.setText("Confirm Password:");

        contact_no.setText("Contact number:");

        contact_no_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_no_txtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reg_panelLayout = new javax.swing.GroupLayout(reg_panel);
        reg_panel.setLayout(reg_panelLayout);
        reg_panelLayout.setHorizontalGroup(
            reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reg_panelLayout.createSequentialGroup()
                        .addComponent(pos_lab)
                        .addGap(73, 73, 73)
                        .addComponent(pos_combox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(reg_panelLayout.createSequentialGroup()
                        .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastname_lab)
                            .addComponent(firstname_lab)
                            .addComponent(crm_pwd_lab))
                        .addGap(32, 32, 32)
                        .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstname_txt)
                            .addComponent(lastname_txt)
                            .addComponent(pwd_txt)
                            .addComponent(email_txt)
                            .addComponent(crm_pwd_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)))
                    .addGroup(reg_panelLayout.createSequentialGroup()
                        .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email_lab)
                            .addComponent(pwd_lab)
                            .addComponent(addr_lab)
                            .addComponent(contact_no))
                        .addGap(47, 47, 47)
                        .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contact_no_txt)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        reg_panelLayout.setVerticalGroup(
            reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reg_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email_lab)
                    .addComponent(email_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pwd_lab)
                    .addComponent(pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crm_pwd_lab)
                    .addComponent(crm_pwd_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstname_lab)
                    .addComponent(firstname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastname_lab)
                    .addComponent(lastname_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact_no)
                    .addComponent(contact_no_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addr_lab)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(reg_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos_combox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pos_lab))
                .addContainerGap())
        );

        firstname_lab.getAccessibleContext().setAccessibleName("first_name_lab");
        firstname_txt.getAccessibleContext().setAccessibleName("first_name_txt");
        firstname_txt.getAccessibleContext().setAccessibleDescription("");
        lastname_lab.getAccessibleContext().setAccessibleName("last_name_lab");
        lastname_txt.getAccessibleContext().setAccessibleName("last_name_lab");
        pos_combox.getAccessibleContext().setAccessibleName("");
        crm_pwd_txt.getAccessibleContext().setAccessibleName("");

        crm_reg_but.setText("Confirm");
        crm_reg_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crm_reg_butActionPerformed(evt);
            }
        });

        bac_but.setText("Back");
        bac_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bac_butActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reg_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(reg_label, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(379, 379, 379))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(crm_reg_but, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bac_but, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reg_label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crm_reg_but, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bac_but, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        reg_label.getAccessibleContext().setAccessibleName("Reg_label");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_txtActionPerformed
        
    }//GEN-LAST:event_firstname_txtActionPerformed

    private void lastname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastname_txtActionPerformed
        
    }//GEN-LAST:event_lastname_txtActionPerformed

    private void pos_comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pos_comboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pos_comboxActionPerformed
    
     
   
    
    
    
    private void crm_reg_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crm_reg_butActionPerformed
        //create object register
        String email = email_txt.getText();
        char[] pwd = pwd_txt.getPassword();
        char[] crm_pwd = crm_pwd_txt.getPassword();  
        String firstname = firstname_txt.getText();      
        String lastname = lastname_txt.getText();
        String address = addr_txt.getText();
        String position = (String)pos_combox.getSelectedItem();
        
        int contact_no;
        try 
        {
            contact_no = Integer.parseInt(contact_no_txt.getText());
            
        }  
        catch (Exception e) 
        { 
                JOptionPane.showMessageDialog(this, "Contact number is compulsory and must be INTEGER! Please type again...",
                        "Error: Contact number", JOptionPane.ERROR_MESSAGE);
                contact_no_txt.setText("");
                return;
        }
        
        //passwords are matched
        if(Arrays.equals(pwd, crm_pwd)){ //passwords is matched
            String formattedString_password = Arrays.toString(pwd)
                .replace(",", "")  //remove the commas
                .replace("[", "")  //remove the open bracket
                .replace("]", "")  //remove the close bracket
                .replace(" ", "") //remove the spacebar
                .trim();
            String password = formattedString_password;
            
            if (JOptionPane.showConfirmDialog(null, "Please click [Yes] if CONFIRMED." + "\n" +
                        "Email: " + email + "\n" +
                        "First name: " + firstname + "\n" + 
                        "Last name: " + lastname + "\n" +
                        //"Identification number: " + ic_no + "\n" +
                        "Contact number:" + contact_no + "\n" +
                        "Address: " + address + "\n" +
                        "Position: " + position, "Profile Information Confirmation!",
                 
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null,"Register successfully" + "\n" +
                        "Email: " + email + "\n" +
                        "First name: " + firstname + "\n" + 
                        "Last name: " + lastname + "\n" +
                        //"Identification number: " + ic_no + "\n" +
                        "Contact number:" + contact_no + "\n" +
                        "Address: " + address + "\n" +
                        "Position: " + position);
                
                User user = new User();
                user.user_register(email,password,firstname,lastname,contact_no,address,position);
                Login log = new Login();
                log.setVisible(true);
                this.setVisible(false);
            } else {
             JOptionPane.getRootFrame().dispose();   
            }
        }
        else{
            //passwords are not matched
            JOptionPane.showMessageDialog(null,"Please make sure your passwords are matched!");
            pwd_txt.setText("");
            crm_pwd_txt.setText("");     
        }
    }//GEN-LAST:event_crm_reg_butActionPerformed

    private void contact_no_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_no_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_no_txtActionPerformed

    private void bac_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bac_butActionPerformed
        this.setVisible(false);
        Login log = new Login();
        log.setVisible(true);
    }//GEN-LAST:event_bac_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addr_lab;
    private javax.swing.JTextArea addr_txt;
    private javax.swing.JButton bac_but;
    private javax.swing.JLabel contact_no;
    private javax.swing.JTextField contact_no_txt;
    private javax.swing.JLabel crm_pwd_lab;
    private javax.swing.JPasswordField crm_pwd_txt;
    private javax.swing.JButton crm_reg_but;
    private javax.swing.JLabel email_lab;
    private javax.swing.JTextField email_txt;
    private javax.swing.JLabel firstname_lab;
    private javax.swing.JTextField firstname_txt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lastname_lab;
    private javax.swing.JTextField lastname_txt;
    private javax.swing.JComboBox<String> pos_combox;
    private javax.swing.JLabel pos_lab;
    private javax.swing.JLabel pwd_lab;
    private javax.swing.JPasswordField pwd_txt;
    private javax.swing.JLabel reg_label;
    private javax.swing.JPanel reg_panel;
    // End of variables declaration//GEN-END:variables
}
